### ISSUE TITLE
Setup SonarQube and SonarScanner

### ISSUE THREAD

**Issue by EvanMateo7** [MichelRahme/ConcordiaNavigation#106]
Setup SonarQube and SonarScanner to scan the Flutter project

**Comment by RdtBui** [comment]
I managed to setup SonarQube with the flutter plugin from https://github.com/insideapp-oss/sonar-flutter on a Debian Linux system. SonarQube is functional with the plugin. Re-installing Dart SDK for an CI environment on Windows might have caused issues that has yet to be solved. We will retrieve SonarQube data entirely from my laptop for now.
