### ISSUE TITLE
Change campus building highlights colour as per PO's request

### ISSUE THREAD

**Issue by MichelRahme** [MichelRahme/ConcordiaNavigation#109]
Right now campus buildings can look like parks on the map because of the green colour. We will be changing the colour from green to maroon.

**Comment by kajanthyS** [comment]
This colour red is kind of harsh. I will change it. 
![image (1)](https://user-images.githubusercontent.com/35846357/76997880-7030a300-692a-11ea-90e4-e82ced2b045a.png)
