### ISSUE TITLE
AT: S-2 - As a user, I want to be able to see campus building information when I tap on Concordia buildings.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#132]
This acceptance test is in reference to issues #93, #110, and #117
PO feedback addressed in AT issue #180

**Acceptance Criteria** 

**Given**

- the map is open
- the campus buildings are highlighted

**When** 

- I tap on a campus building initial 

**Then**

- information of that building is shown

**Steps**
1. Once the map is open, click on the menu button and select the "Campus" button. 
2. Select the campus you wish to view.
3. Click on the "Toggle Building Highlights" for highlights to be turned on/off
4. Click on the initial of a building to see building information 
5. Tap anywhere outside of the sheet to close the information card
6. To view information about a different campus, switch between campus using the switch campus button or using the campus submenu located in the sidebar

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147240-9e6e9a80-7d91-11ea-97f0-bdb3825a3133.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED
