### ISSUE TITLE
AT: S-1.4 - As a user, I want to be able to see campus buildings highlighted.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#133]
This acceptance test is in reference to issues #85, #109, and #117

**Acceptance Criteria** 

**Given** 

- The map is open 

**Then** 

- Campus buildings should be highlighted 

**Steps** 

1. Once the map is open, click on the menu button and select the "Campus" button.
2. Select the campus you wish to view.
3. Click on the sun icon for highlights to be turned on/off

**Comment by mkshiblu** [comment]
ACCEPTED

**Comment by andrelegault** [comment]
Sorry I mean #113, not #133!
