### ISSUE TITLE
AT: S-10.1 - As a user, I want to find the nearest point of outdoor interest (restaurants, stores, bus stops, etc.).

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#134]
This acceptance test is in reference to issues #25 and #35

**Acceptance Criteria** 

**Given** 

- that I’ve pressed the points of interests button on the sidebar menu

**Then** 

- a list of points of outdoor interests should be displayed on the screen.

**Steps** 

1. Select the menu icon 
2. Select “Outdoor Interest” button located in the sidebar menu
3. Once the list of outdoor interests is displayed, select the directions button to receive an itinerary starting from your current location
4. Alternatively, a starting location can be selected by tapping on the "Start Destination" field
5. To see a visual trajectory drawn out on the map, pull down on the tab located at the top of the directions card

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147613-340a2a00-7d92-11ea-8844-2318e6814921.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED. Nice representation of the POIs as List
