### ISSUE TITLE
AT: S-3.2 - As a user, I want to be able to obtain directions to my destination based on my current location.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#135]
This acceptance test is in reference to issue #22
PO feedback is addressed in AT issue #187

**Acceptance Criteria** 

**Given** 

- that the map is open

**When** 

- I choose a destination location

**Then** 

- the map displays an itinerary or a list of itineraries as well as a visual trajectory on the map, using my current location as the start location.

**Steps** 

1. Click on the search icon 
2. Type in a Concordia location
3. Select a destination from the outputted list 
4. A list of directions will be outputted, to switch between transportation modes, select the desired transportation icon
5. To view the visual trajectory displayed on the map, pull down on the tap located at the top of the directions card

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79173103-9aa83b80-7dc4-11ea-8268-6cfc20395611.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED. Perhaps the bottom bar could have been minimized first instead of fully open. If the user wants to see full details they have to maximize it.

**Comment by MichelRahme** [comment]
> ACCEPTED. Perhaps the bottom bar could have been minimized first instead of fully open. If the user wants to see full details they have to maximize it.

@mkshiblu Noted. We will certainly do that.
