### ISSUE TITLE
AT: S-3.1 - As a user, I want to be able to select a Concordia end destination in order to get directions.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#142]
This acceptance test is in reference to issue #21

**Acceptance test**

**Given** 

- that the map is open

**When** 

- I choose a Concordia destination location,

**Then** 

- the map displays an itinerary or a list of itineraries as well as a visual trajectory on the map, using my current location as the start location.

**Steps**

1. Tap on the search icon on the app bar.
2. Input a destination location (Only Concordia destinations are allowed).
3. Select a location from the list.
4. A list of directions will be outputted, to switch between transportation modes, select the desired transportation icon
5. Pull down on the top tab to view a visual trajectory is displayed on the map. 

**Example**
 
![AT-S3 1](https://user-images.githubusercontent.com/46969984/79147269-b0503d80-7d91-11ea-8236-d4acc6f28369.gif)

**Comment by mkshiblu** [comment]
ACCEPTED. It's sometimes not very much clear where is my destination name when I minimize the bottom bar.

**Comment by MichelRahme** [comment]
> ACCEPTED. It's sometimes not very much clear where is my destination name when I minimize the bottom bar.

@mkshiblu Okay sure, we can make the bottom bar a bit bigger when it's minimized so the destination will be visible.
