### ISSUE TITLE
AT:  S-3.5 - As a user, I want to see the shuttle bus schedule

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#144]
This acceptance test is in reference to issue #78

**Acceptance Criteria** 

**Given** 
- That the direction panel is open

**When** 
- I press on the “View Schedule” button, 

**Then** 
- a sheet with the shuttle bus schedule is displayed on my screen.

**Steps**

1. Tap on the search icon on the app bar (this can also be done using the outdoor interests).
2. Input a destination location (Only Concordia locations allowed).
3. Select a location from the list.
4. Tap on the “View Schedule” button, to view the shuttle schedule listed in a table. Selecting the campus direction (SGW to Loyola or Loyola to SWG), will highlight the corresponding schedule. 

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79146968-3455f580-7d91-11ea-83f0-84636255ab23.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED
