### ISSUE TITLE
AT: S-7.1: As a user, I want my next class to be displayed in my calendar.

### ISSUE THREAD

**Issue by EvanMateo7** [MichelRahme/ConcordiaNavigation#145]
This acceptance test is in reference to issue #28

**Acceptance Criteria**

**Given**
- that I am in the schedule page and that the app has access to the device’s calendar

**Then**
- the list of my scheduled classes are displayed

**Steps**

1. Open the drawer menu on the left side of the screen.
2. Select “Schedule”.
3. Select “Allow” for permissions to your device calendar.

> **NOTE**
> 4 uppercase letter followed by either (a space, dash or nothing) finally followed by 3 digits.

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147540-189f1f00-7d92-11ea-8fb8-9187250a4f2c.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED
