### ISSUE TITLE
AT: S-7.2: As a user, I want the location of my next class to be displayed in my calendar.

### ISSUE THREAD

**Issue by EvanMateo7** [MichelRahme/ConcordiaNavigation#146]
This acceptance test is in reference to issue #29 
Related user story #145 

**Acceptance Criteria**

**Given**
- that I am in the schedule page and that the app has access to the device’s calendar

**Then**
- the list of my scheduled classes are displayed (class title must be of valid format)

**Steps**

1. Open the drawer menu on the left side of the screen.
2. Select “Schedule”.
3. Select “Allow” for permissions to your device calendar.
4. Tap on the “Directions” button (May take a couple of seconds).

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147570-25237780-7d92-11ea-87ab-45c28551116c.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED
