### ISSUE TITLE
Bug where if navigating from H9 to other floors, a small path is drawn on the H8 floor

### ISSUE THREAD

**Issue by MichelRahme** [MichelRahme/ConcordiaNavigation#162]
# To reproduce: 

- choose start location as any H9 classroom 
- choose destination as any other floor (other than H8)
- a small path will be drawn on the H8 floor. It should not.

**Comment by andrelegault** [comment]
Could you include a screenshot of the bug just so we know what to look for?

**Comment by MichelRahme** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 17 19 57](https://user-images.githubusercontent.com/25441876/78606166-e0945b00-782a-11ea-93d3-bca6519c7f5d.png)

**Comment by andrelegault** [comment]
Cool, thanks!
