### ISSUE TITLE
Revamp Class Hierarchy

### ISSUE THREAD

**Issue by andrelegault** [MichelRahme/ConcordiaNavigation#166]
It would be good to have a class hierarchy that would model the common objects users encounter (university, building, etc.). This was discussed at the beginning of the term but was never fully implemented in code. The end goal would be to reduce code duplication and take advantage of OOP concepts like polymorphism, inheritance, etc.

**Comment by WindOfRussia** [comment]
for the record, our definition of refactor covers all of the above:
![image](https://user-images.githubusercontent.com/6550234/79293454-ccdb9b00-7ea1-11ea-996b-d1e015890ff5.png)
