### ISSUE TITLE
AT:  S-1.1 - As a user, I want to be able to see my location on campus.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#171]
This acceptance test is in reference to issues #19, #16

**Acceptance Criteria** 

**Given** 

- that the map is open

**When** 

- I click the campus I’m currently in

**Then** 

- I should be able to see my current location marked by a single dot on campus.

**Steps** 

1. Open the app, the app should launch and Google maps opens with my current location marked by a single dot on campus.

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79172084-ba8a3000-7dc1-11ea-8cd7-ea08e2830676.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED.
