### ISSUE TITLE
AT:  S-1.2 - As a user, I want to see the building I am currently in.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#172]
This acceptance test is in reference to issues #17, #19

**Acceptance Criteria** 

**Given** 

- that the map is open

**When** 

- I am inside of a campus building, 

**Then** 

- I should see my current location within the perimeter of the building. 

**Steps** 

1. Open the app, the app should launch and Google maps opens with my current location within the perimeter of the building.

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79172109-cc6bd300-7dc1-11ea-9116-80b865dbbe59.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED.
