### ISSUE TITLE
AT:  S-1.3 - As a user, I want to switch between Loyola and SGW campus.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#173]
This acceptance test is in reference to issues #18, #19

**Acceptance Criteria** 

**Given** 

- that the map is open

**When** 

- I open the drawer menu and select a campus,

**Then** 

- the map should focus/zoom on the selected campus

**Steps** 

1. Open the app.
2. Open the drawer menu on the left side of the screen by clicking on the menu button 
3. Click the "Campus" sub menu
4. Click on a campus name
5. Alternatively, the switch button can used to switch in-between campuses

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147782-7b90b600-7d92-11ea-87f7-195a4eb0a932.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED.
