### ISSUE TITLE
 S-3.3 - As a user, I want to know if I’m able to make the next shuttle bus between campuses.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#174]
This acceptance test is in reference to issues #23, #25

**Acceptance Criteria** 

**Given** 

- that the map is open

**When** 

- I choose the shuttle bus stop as the destination location,

**Then** 

- the map displays an itinerary or a list of itineraries, using my current location as the start location
and the next available shuttle bus is shown at the bottom.

**Steps** 

1. Open the app
2. Tap on the search icon on the app bar
3. Input a destination
4. When the directions panel pulls up, the next shuttle bus time is displayed at the bottom

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147312-c1994a00-7d91-11ea-962b-ffa133a6e4d3.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED.
