### ISSUE TITLE
AT: S-3.4 - As a user, I want to be able to choose a method of transportation among given options

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#175]
This acceptance test is in reference to issues #24, #25

**Acceptance Criteria** 

**Given** 

- that I am on the directions panel 

**When** 

- I choose a mode of transportation,

**Then** 

- the map displays an itinerary or a list of itineraries using the chosen mode of transportation.

**Steps** 

1. Open the app
2. Tap on the search icon on the app bar
3. Input a destination
4. When the directions panel pulls up, tap on the icon on the top of the page representing the desired mode of transportation e.g. car icon for driving mode.

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147356-d1189300-7d91-11ea-9870-634926502bf5.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED. Thanks for adding the gifs. Really helpful for testing. May I ask which tool you have used to create the gifs? I myself would like to use some easy tools like these.

**Comment by a-drew** [comment]
> ACCEPTED. Thanks for adding the gifs. Really helpful for testing. May I ask which tool you have used to create the gifs? I myself would like to use some easy tools like these.

@mkshiblu here you go: https://ezgif.com/video-to-gif
