### ISSUE TITLE
AT:  S-4 - As a user, I want the app to change between English and French based on my device’s configuration.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#176]
This acceptance test is in reference to issue #11

**Acceptance Criteria** 

**Given** 

- that my device allows language selection,

**When** 

- I navigate to my device language settings
- and I choose a language (English or French)
- and I open the application,

**Then** 

- all text displayed by the application should be in the chosen language.

**Steps** 

1. Change the device’s language (English or French)
2. Open the app

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147471-f86f6000-7d91-11ea-933a-f76c65942055.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED.
