### ISSUE TITLE
AT:  S-6 - As a user, I want to be able to use the application in colourblind mode.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#177]
This acceptance test is in reference to issue #27

**Acceptance Criteria** 

**Given** 

- that my device allows colour correction or colourblind mode,

**When** 

- I navigate to my device visibility settings
- and I choose a colour correction configuration or enable colour blind mode
- and I open the application,

**Then** 

- the application’s colours should reflect the chosen colour correction configuration or be in colourblind mode

**Steps** 

1. Change the device's colour configuration.
2. Open the app

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147507-091fd600-7d92-11ea-8ee0-d088dc9447ef.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED.  Good job.
