### ISSUE TITLE
AT: S-1.4 - As a user, I want to be able to see campus buildings highlighted.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#180]
This acceptance test is in reference to issues #85, #109, and #117
This AT addresses the feedback given by the PO in issue #133

**Acceptance Criteria** 

**Given** 

- The map is open 

**Then** 

- Campus buildings should be highlighted 

**Steps** 

1. Once the map is open, click on the menu button and select the "Campus" button.
2. Select the campus you wish to view.
3. Click on the "Toggle Building Highlights" for highlights to be turned on/off

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79147184-8c8cf780-7d91-11ea-9164-cb37e1657c62.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED.  Although I think the previous color theme (green if remember correctly) was better than the current one. But this one is not bad either.
