### ISSUE TITLE
AT:  S-9.2: As a user, I want to obtain the shortest path between the starting room and destination room.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#184]
This acceptance test is in reference to issue #33, #34

**Acceptance Criteria** 

**Given** 

- that I am in the indoor map page, 
- and that I’ve given a starting room and destination room, 

**Then** 

- I should get directions to the destination room from the starting room using the shortest path.

**Steps** 

1. Click on the search icon 
2. Input a indoor starting point and destination 
Note: Only floors H1, H8, H9, and MB1 are supported

**Example**
![](https://i.imgur.com/q4qFnKH.gif)

**Comment by Alex-Hayeur** [comment]
Video is recorded, currently editing and turning into gif.

**Comment by mkshiblu** [comment]
ACCEPTED. I liked how you have laid out the indoor maps. However, if you continue to develop the app, I would suggest adding the floor no. on the actual floor plan so that it's easy for the user to understand which floor plans they are currently viewing.

**Comment by m-rahme** [comment]
> ACCEPTED. I liked how you have laid out the indoor maps. However, if you continue to develop the app, I would suggest adding the floor no. on the actual floor plan so that it's easy for the user to understand which floor plans they are currently viewing.

Yes, that makes sense. Thank you for the feedback.
