### ISSUE TITLE
AT: S-10.2: As a user, I want to find the nearest point of indoor interest (washroom, elevator, stairs, etc.).

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#186]
This acceptance test is in reference to issues #36

**Acceptance Criteria** 

**Given** 

- I am on the indoor map

**Then** 

- I can view the indoor interests (washrooms, water fountains, stairs, elevators) highlighted on the map 

**Steps** 

1. Select "Indoor" button
2. Select floors to view highlighted indoor interests
Note: Only floors H1, H8, H9, and MB1 are supported

**Example**

<img src="https://user-images.githubusercontent.com/46969984/79172721-7b5cde80-7dc3-11ea-85c3-533b14cb9228.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED
