### ISSUE TITLE
AT: S-3.1: As a user, I want to be able to select a Concordia start location and a Concordia end destination in order to get directions.

### ISSUE THREAD

**Issue by kajanthyS** [MichelRahme/ConcordiaNavigation#187]
This acceptance test is in reference to issue #21
Updated acceptance test of #142 

**Acceptance test**

**Given** 

- that the map is open

**When** 

- I choose a Concordia start location,

- I choose a Concordia destination location,

**Then** 

- the map displays an itinerary or a list of itineraries as well as a visual trajectory on the map, using my current location as the start location.

**Steps**

1. Tap on the search icon on the app bar.
2. Input a start location (Only Concordia destinations are allowed).
3. Select a location from the list.
4. Input a destination location (Only Concordia destinations are allowed).
5. Select a location from the list.
6. A list of directions will be outputted, to switch between transportation modes, select the desired transportation icon
7. Pull down on the top tab to view a visual trajectory is displayed on the map. 

**Example**
 
<img src="https://user-images.githubusercontent.com/46969984/79147269-b0503d80-7d91-11ea-8236-d4acc6f28369.gif" width="300">

**Comment by mkshiblu** [comment]
ACCEPTED
