### ISSUE TITLE
S-3.1: As a user, I want to be able to select a Concordia start location and a Concordia end destination in order to get directions.

### ISSUE THREAD

**Issue by waynet022** [MichelRahme/ConcordiaNavigation#21]
Once the starting point and destination are entered, the directions are displayed.

Details:
1. A directions button is located at the bottom right of the screen. 
Pressing it will prompt 2 inputs for locations. The top input is for the starting location while the bottom input will take the destination input.
1. Location inputs can be a building address or a classroom number. 
1. If it’s a classroom, the building acts as the destination.
1. The available locations can only be within either the Loyola campus or the SGW campus.
1. Available Start locations are only within the Loyola campus or SGW campus

Acceptance Criteria:
- [x] Given that the map is open, when I choose a start location and a destination location, then the map displays an itinerary or a list of itineraries to choose from. 
- [x] When picking an itinerary, the map with show a list of directions and draw the path on the map. #84

**Comment by Alex-Hayeur** [comment]
Updated to reflect the requirements properly (Only Concordia buildings should be available start locations to search aside from user's current location)

**Comment by WindOfRussia** [comment]
@MichelRahme @andrelegault same thing here, now that the bugs are handled via PR #99, is this passing the acceptance criteria?

**Comment by andrelegault** [comment]
Given 

> Location inputs can be a building address or a classroom number.
If it’s a classroom, the building acts as the destination.

We don't support rooms yet so there's still work to do to before this can be closed
