### ISSUE TITLE
Epic S-3: As a user, I want to be able to get outdoor directions.

### ISSUE THREAD

**Issue by waynet022** [MichelRahme/ConcordiaNavigation#25]
Details:
1. The outdoor directions can start on the user’s current location or a campus building location. 
1. The destination can only be a building campus building or an outdoor point of interest.

Dependencies:
#21, #22, #23, #24 

Acceptance Criteria:
- [ ] Given that the map is open, when I choose a start location and a destination location, then the map displays an itinerary or a list of itineraries.

**Comment by WindOfRussia** [comment]
Reopened to reflect that PO requested some changes. view #84
