### ISSUE TITLE
S-7.2: As a user, I want the location of my next class to be displayed in my calendar.

### ISSUE THREAD

**Issue by waynet022** [MichelRahme/ConcordiaNavigation#29]
The calendar outputs the next destination.
Acceptance Criteria
- [x] Display information about the building where the class will be held.
- [x] When a user presses on directions for a course, it provides the course's room as a direction destination

Details:
The calendar outputs the location of the next class and has a direction button to output directions to the class from the user’s current location. 
The directions output will include outdoor and indoor directions.

**Comment by WindOfRussia** [comment]
Covered in the #127 PR
