### ISSUE TITLE
Epic S-7: As a user, I want to be able to connect my calendar to set my next scheduled destination.

### ISSUE THREAD

**Issue by waynet022** [MichelRahme/ConcordiaNavigation#30]
As a user, I want to be able to connect my calendar to set my next scheduled destination.

Acceptance Criteria: 
- [x] Given that I am in the schedule menu, when I press on directions from one of my courses, then I should get directions on the map to my course’s room destination.

**Comment by WindOfRussia** [comment]
Covered through #28 #29 via PR #127
