### ISSUE TITLE
S-10.1: As a user, I want to find the nearest point of outdoor interest (restaurants, stores, etc.).

### ISSUE THREAD

**Issue by waynet022** [MichelRahme/ConcordiaNavigation#35]
The user can see the points of interest within the campus perimeters.

**Comment by Alex-Hayeur** [comment]
- [ ] Prepare data (.json) and assets (pictures of locations & reviews)

- [ ] Create UI to show the building information

- [ ] Show directions to Point of Interest (based on the json)
