### ISSUE TITLE
Software Implementation

### ISSUE THREAD

**Issue by waynet022** [MichelRahme/ConcordiaNavigation#46]
-Quality of source code reviews
-Correct implementation of design patterns
-Respect of code conventions
-Design quality as measured by number of classes/packages, module size, coupling, cohesion
-Quality of source code documentation
-Refactoring activity documented in commit messages
-Quality detail of commit messages
-Use of feature branches
-Use of atomic commits
-linking of commits to issues (user stories)
-

**Comment by RdtBui** [comment]
Not sure if all of those goes in the document or not. I also need to wait until the coding for sprint 2 is over to document the "real" values of the metrics, number of classes, cohesion, etc. I emailed the teacher about what goes in the doc and what doesn't. Might take a few more days depending how fast the teacher replies which will might result in a bit of delay. Already started to make a "template" for my part.

**Comment by RdtBui** [comment]
There isn't much to document for software implementation so this issue is basically done
