### ISSUE TITLE
5. Software Architecture

### ISSUE THREAD

**Issue by juliabaz** [MichelRahme/ConcordiaNavigation#6]
1. Domain Diagram (uml class diagram) + description
2. Component diagram + description
3. Description of external libraries the project depends on
4. Advantages of libraries over alternative ones

**Comment by andrelegault** [comment]
User  - has a location (GPS)  - has a destination (coordinates, search)  Buildings Campus (SGW/Loyola)  - has an outline?  - has coordinates  - accessibility description  - list of services    States:   - Default: show current position, search and map.   - Search: look up a location, room, etc.   - Location Details: show a page with information   - Directions (outdoor): show options (bus, walk, drive), trace path to destination.   - Directions (indoor) trace path between rooms & floors.    - Settings Page   - Schedule Page (itinerary?)   -
