### ISSUE TITLE
S-3.5: As a user, I want to be able to see the Shuttle Bus Schedule.

### ISSUE THREAD

**Issue by MichelRahme** [MichelRahme/ConcordiaNavigation#78]
User will be able to check the full shuttle bus schedule from **SGW** to **Loyola** and vice versa.

Details:
A sheet will display the Concordia shuttle bus schedule. 
The table can be accessed from the sidebar

Acceptance Criteria:
- [ ] Given that the sidebar is open, when I press on the shuttle bus schedule, a sheet with the shuttle bus schedule is displayed on my screen.

**Comment by WindOfRussia** [comment]
@MichelRahme @andrelegault so by closing #95 and #88, is this resolved?

**Comment by andrelegault** [comment]
I don't think so

**Comment by andrelegault** [comment]
Although I haven't really touched this part of the code, so I couldn't say.

**Comment by MichelRahme** [comment]
> @MichelRahme @andrelegault so by closing #95 and #88, is this resolved?

No, i still need to setup the schedule table. I'm moving this back to `In Progress`.

**Comment by MichelRahme** [comment]
Assigned @Alex-Hayeur and @RdtBui to work on this after my failed attempt. 
Moving it back to backlog.
