### ISSUE TITLE
Improve Transit Directions

### ISSUE THREAD

**Issue by MichelRahme** [MichelRahme/ConcordiaNavigation#81]
Parse all sub-directions from Json

Acceptance criteria: 
- [ ] Parse the subdirections information from google api
- [ ] Display sub direction steps in the directions list (UI)
- [ ] Display sub direction lines drawn on the map (UI)

**Comment by waynet022** [comment]
Transit directions missing
add missing subdirections

**Comment by MichelRahme** [comment]
Wont Fix
