### ISSUE TITLE
Show generated directions on the map

### ISSUE THREAD

**Issue by MichelRahme** [MichelRahme/ConcordiaNavigation#84]
Use polylines to show the generated directions on the map.

Acceptance Criteria: 
- [ ] Once an itinerary is selected, there is also a drawn path showing the directions the user must follow to reach the destination.

**Comment by waynet022** [comment]
Show actual polylines on map for directions

**Comment by MichelRahme** [comment]
The path is now generated on the map. Going to close this issue. Thanks
