### ISSUE TITLE
S-2x Refactor Building Markers

### ISSUE THREAD

**Issue by waynet022** [MichelRahme/ConcordiaNavigation#93]
Acceptance criteria : 
- [x] Update building markers to PO standards

**Comment by WindOfRussia** [comment]
@MichelRahme hey, this isn't attached to a milestone yet?

**Comment by MichelRahme** [comment]
@WindOfRussia This is scheduled for sprint 3. 

We need to change the current markers to transparent ones or ones with building names. (Whichever works better).

**Comment by WindOfRussia** [comment]
Ok got it, maybe we can reuse the same display mechanism for points of interest (#37)

**Comment by WindOfRussia** [comment]
@waynet022 Let us know when this is in progress.

**Comment by MichelRahme** [comment]
Refactoring done 👍

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-20 at 17 14 34](https://user-images.githubusercontent.com/25441876/77206871-69db2c00-6ace-11ea-9cec-1cfd9662e7c1.png)
