### ISSUE TITLE
Quality Metrics 

### ISSUE THREAD

**Issue by Alex-Hayeur** [MichelRahme/ConcordiaNavigation#94]
Describe your strategies to improve the metrics 
Comparison with previous metrics (metrics evolution) [optional for Sprint #3, only if you have metrics from Sprint #2, mandatory for Sprint #4]

- [x] Install and use SonarQube #106 
https://github.com/insideapp-oss/sonar-flutter
- [ ] Report Code Duplication
- [ ] Report Code Documentation
- [ ] Report Size
- [ ] Report Coupling
- [ ] Report Cohesion
- [ ] Code Smells & Technical Debt
- [ ] Strategy to Improve
- [ ] Retrospective (for sprint 4)

**Comment by EvanMateo7** [comment]
When running sonar-scanner I get the same issue as 
https://github.com/insideapp-oss/sonar-flutter/issues/3

![image](https://user-images.githubusercontent.com/23142137/76708654-eb961880-66ce-11ea-828f-b82b4bc03a86.png)

**Comment by WindOfRussia** [comment]
@EvanMateo7 thanks for keeping us posted on progress <3
