### ISSUE TITLE
Refactor getNextShuttle

### ISSUE THREAD

**Issue by andrelegault** [MichelRahme/ConcordiaNavigation#95]
The `getNextShuttle`  (in `lib/providers/shuttle_data.dart`) function currently only accepts a `String` representing whether we should check for Loyola's next shuttle bus passage or SGW's next shuttle bus passage. This isn't very good in terms of extensibility as well as testing.

The refactor would add an optional DateTime parameter whose default value is the current time.

**Comment by WindOfRussia** [comment]
Linked to #78 - Shuttle Schedule Page
