### ISSUE TITLE
UI Enhancement for Directions List

### ISSUE THREAD

**Issue by MichelRahme** [MichelRahme/ConcordiaNavigation#98]
**Update User Interface for the generated directions to meet to PO's requirements.** 

Acceptance Criteria: 
- [x] From the map, when a supported destination (Concordia building) is selected, the user should be able to get the directions list + itinerary lines on the map for said building from their current location. This will come in the form of a **drawer** that can be pulled up/down from the bottom of the screen, with the map in the background containing the itinerary lines.

**Comment by WindOfRussia** [comment]
closed via PR #99, passed acceptance criteria
